services:
  reactos:
    image: erkinalp/reactose
    container_name: reactos
    environment:
      VERSION: "0.4.15"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./reactos:/storage
    restart: always
    stop_grace_period: 2m
